name: Deploy to WordPress Server

on:
  push:
    branches:
      - master  # Kun push til master udløser workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Tjek koden ud fra GitHub repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Installér PHP senere
   
    # - name: Setup PHP
    #   uses: shivammathur/setup-php@v2
    #   with:
    #     php-version: '8.0'

    # Deploy via FTP
    - name: Deploy via SFTP
      uses: appleboy/scp-action@v0.1.7
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        source: ./
        target: /public_html/wp-content/themes/silverjournal/
